# Generated by Django 4.1.4 on 2022-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('customer_mail', models.EmailField(max_length=254)),
                ('customer_type', models.CharField(max_length=50)),
                ('submitted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('device_state', models.CharField(max_length=10)),
                ('device_problem', models.CharField(max_length=100)),
            ],
        ),
    ]
