# Generated by Django 4.1.4 on 2022-12-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='unique_id',
        ),
    ]
